apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: task-openshift-command
spec:
  steps:
  - name: version
    image: docker.io/piyushgarg/oc-image
    command:
    - /usr/local/bin/oc
    args: ["version"]
  - name: listpods
    image: docker.io/piyushgarg/oc-image
    command:
    - /usr/local/bin/oc
    args: ["get", "pods"]
