apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  name: task-run-openshift-command-s
spec:
  taskRef:
    name: task-openshift-command-s
  inputs:
    resources:
      - name: clusterdetails
        resourceRef:
          name: aws-cluster
